api_platform:
    title: Shroomer
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
        
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            
    use_symfony_listeners: true
    enable_link_security: true
    
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
                
